name: Report
on:
  push:
  schedule:
    - cron: '15 * * * *'
  watch:
    types: [started]
  workflow_dispatch:
jobs:
  build:
    if: github.repository == 'BeeHiveCyberSecurity/WAF-IPDB'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Report
      run: python main.py
      env:
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
        CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        ABUSEIPDB_API_KEY: ${{ secrets.ABUSEIPDB_API_KEY }}
